frontend_base_url: http://127.0.0.1:4200
allow_origins: []

mongo:
  uri: mongodb://127.0.0.1:27017/depot

oauth2:
  server_metadata_url: 'http://127.0.0.1:8000/.well-known/openid-configuration'
  client_id: 'depot'

mail:
  host: localhost
  sender: "admin@localhost"
  #port: 25
  #ssl: false
  #starttls: false
  #keyfile: null
  #certfile: null
  #user: ""
  #password: ""
