[tool.poetry]
name = "depot-server"
version = "1.0.3"
description = ""
authors = ["Lukas Voegtle <lukas@infornautik.de>"]

[tool.poetry.dependencies]
python = "^3.12"
pydantic = "^2.11"
fastapi = "^0.115"
motor = "^3"
oyaml = "^1"
authlib = "^1"
pytz = "^2025.2"
uvicorn = "^0.34"
httpx = "^0.28"
mako = "^1"
aiosmtplib = "^4"
python-multipart = "^0.0"
pillow = "^11"

[tool.poetry.dev-dependencies]
pytest = "^8"
pytest-mypy = "^1"
pytest-flake8 = "^1"
requests = "^2"
mongomock = "^4"
types-pytz = "^2025"
types-requests = "^2"

[tool.poetry.scripts]
migrate = "depot_server.db.migrate:main"

[tool.poetry.group.dev.dependencies]
bump-pydantic = "^0.8.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
