frontend_base_url: http://127.0.0.1:4201
allow_origins: []

return_reservation_reminder_cron_time: 10:00:00
reservation_code_length: 6
reservation_code_chars: "123456789"
reservation_automatic_return: True
debug: true
log_level: "INFO"
device_api_key: 'abcdefg'

mongo:
  uri: mongodb://127.0.0.1:27017/depot

oauth2:
  server_metadata_url: 'http://127.0.0.1:8000/.well-known/openid-configuration'
  client_id: 'depot'
  client_secret: 'i0CQLpy95zp4yj1UgdzJCTvFkXLK0ZwI'
  request_token_url: ""
  request_token_params: ""
  access_token_url: ""
  access_token_params: ""
  refresh_token_url: ""
  refresh_token_params: ""
  authorize_url: ""
  authorize_params: ""
  api_base_url: ""

mail:
  host: localhost
  sender: "admin@localhost"
  port: 25
  ssl: false
  starttls: false
  keyfile: null
  certfile: null
  user: ""
  password: ""

db:
  engine: "sqlite"
  database: "devdepot.sqlite"


cosmetics:
  tag_default_color: "#000000"