from uuid import uuid4

from tortoise import fields
from tortoise import migrations
from tortoise.fields.base import OnDelete
from tortoise.migrations import operations as ops

from depot_server.db2.common import Condition
from depot_server.db2.models.item.reservation import ReservationState, ReservationType


class Migration(migrations.Migration):
    initial = True

    operations = [
        ops.CreateModel(
            name='AllowedMimeType',
            fields=[
                ('mime', fields.CharField(primary_key=True, unique=True, db_index=True, max_length=50)),
                ('description', fields.TextField(unique=False)),
            ],
            options={'table': 'depot_allowed_mimetype', 'app': 'depot', 'pk_attr': 'mime'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='AssetType',
            fields=[
                ('id', fields.UUIDField(primary_key=True, default=uuid4, unique=True, db_index=True)),
                ('name', fields.CharField(unique=True, max_length=255)),
                ('description', fields.TextField(unique=False)),
            ],
            options={'table': 'depot_asset_type', 'app': 'depot', 'pk_attr': 'id',
                     'table_description': 'Asset Type Model:'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='Asset',
            fields=[
                ('id', fields.UUIDField(primary_key=True, default=uuid4, unique=True, db_index=True)),
                ('mime', fields.ForeignKeyField('depot.AllowedMimeType', source_field='mime_id',
                                                description='The mime type of the asset', db_constraint=True,
                                                to_field='mime', related_name='assets', on_delete=OnDelete.RESTRICT)),
                ('asset_type', fields.ForeignKeyField('depot.AssetType', source_field='asset_type_id',
                                                      description='The type of the asset', db_constraint=True,
                                                      to_field='id', related_name='assets',
                                                      on_delete=OnDelete.RESTRICT)),
                ('created_by', fields.UUIDField(description='The user id who created the asset')),
                ('created_at',
                 fields.DatetimeField(description='The timestamp when the asset was created', auto_now=False,
                                      auto_now_add=False)),
                ('updated_by', fields.UUIDField(description='The user id who updated the asset')),
                ('updated_at',
                 fields.DatetimeField(description='The timestamp when the asset was last updated', auto_now=False,
                                      auto_now_add=False)),
                ('uri',
                 fields.TextField(description='The URI of the asset. Prepend assets on the filesystem', unique=False)),
                ('description', fields.TextField(null=True, description='The description of the asset', unique=False)),
                ('hash_', fields.TextField(description='The sha256 of the asset', unique=False)),
            ],
            options={'table': 'depot_asset', 'app': 'depot', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='ExternalService',
            fields=[
                ('id', fields.UUIDField(primary_key=True, default=uuid4, unique=True, db_index=True)),
                ('created_at', fields.DatetimeField(auto_now=False, auto_now_add=True)),
                ('created_by', fields.UUIDField()),
                ('updated_at', fields.DatetimeField(auto_now=False, auto_now_add=False)),
                ('updated_by', fields.UUIDField()),
                ('reason', fields.TextField(unique=False)),
                ('intern_responsible', fields.TextField(unique=False)),
                ('service_contractor', fields.TextField(unique=False)),
                ('notes', fields.TextField(unique=False)),
            ],
            options={'table': 'depot_external_service', 'app': 'depot', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', fields.UUIDField(primary_key=True, default=uuid4, unique=True, db_index=True)),
                ('parent', fields.ForeignKeyField('depot.ItemGroup', source_field='parent_id', null=True,
                                                  description='Used to build up a tree like structure of groups',
                                                  db_constraint=True, to_field='id', related_name='child',
                                                  on_delete=OnDelete.RESTRICT)),
                ('name', fields.TextField(unique=False)),
                ('description', fields.TextField(unique=False)),
                ('id_prefix', fields.CharField(description='prefix of the external ID', max_length=90)),
                ('id_next', fields.IntField(default=1,
                                            description='The next free numerical suffix that can be given to the next item')),
                ('enforce_exact_item', fields.BooleanField(default=False,
                                                           description='true if the user can only lend a specific item and not any of the group')),
            ],
            options={'table': 'depot_item_group', 'app': 'depot', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='ReportElement',
            fields=[
                ('id', fields.UUIDField(primary_key=True, default=uuid4, unique=True, db_index=True)),
                ('title', fields.CharField(unique=True, max_length=100)),
                ('parent_id', fields.ForeignKeyField('depot.ReportElement', source_field='parent_id_id', null=True,
                                                     db_constraint=True, to_field='id', related_name='child',
                                                     on_delete=OnDelete.CASCADE)),
                ('version', fields.CharField(max_length=50)),
                ('created_at', fields.DatetimeField(auto_now=False, auto_now_add=True)),
                ('created_bv', fields.UUIDField()),
                ('updated_at', fields.DatetimeField(auto_now=False, auto_now_add=False)),
                ('updated_by', fields.UUIDField()),
            ],
            options={'table': 'depot_report_element', 'app': 'depot', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='ReportProfile',
            fields=[
                ('id', fields.UUIDField(primary_key=True, default=uuid4, unique=True, db_index=True)),
                ('name', fields.CharField(unique=True, max_length=100)),
                ('parent_id', fields.ForeignKeyField('depot.ReportProfile', source_field='parent_id_id', null=True,
                                                     db_constraint=True, to_field='id', related_name='child',
                                                     on_delete=OnDelete.CASCADE)),
                ('version', fields.IntField()),
                ('created_at', fields.DatetimeField(auto_now=False, auto_now_add=True)),
                ('created_by', fields.UUIDField()),
                ('updated_at', fields.DatetimeField(auto_now=True, auto_now_add=False)),
                ('updated_by', fields.UUIDField()),
                ('report_elements', fields.ManyToManyField('depot.ReportElement', unique=True, db_constraint=True,
                                                           through='depot_report_profile_depot_report_element',
                                                           forward_key='reportelement_id',
                                                           backward_key='depot_report_profile_id',
                                                           related_name='depot_report_profiles',
                                                           on_delete=OnDelete.RESTRICT)),
            ],
            options={'table': 'depot_report_profile', 'app': 'depot', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='Reservation',
            fields=[
                ('id', fields.UUIDField(primary_key=True, default=uuid4, unique=True, db_index=True)),
                ('name', fields.TextField(unique=False)),
                ('start', fields.DatetimeField(auto_now=False, auto_now_add=False)),
                ('end', fields.DatetimeField(auto_now=False, auto_now_add=False)),
                ('user', fields.UUIDField()),
                ('team', fields.UUIDField(null=True)),
                ('contact', fields.TextField(unique=False)),
                ('is_active', fields.BooleanField()),
                ('reservation_type',
                 fields.CharEnumField(description='TEAM: team\nPRIVATE: private\nEXTERNAL: external',
                                      enum_type=ReservationType, max_length=8)),
                ('reservation_state', fields.CharEnumField(default=ReservationState.RESERVED,
                                                           description='RESERVED: reserved\nINVENTUR: inventur\nMAINTENANCE: maintenance',
                                                           enum_type=ReservationState, max_length=11)),
            ],
            options={'table': 'depot_reservation', 'app': 'depot', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', fields.UUIDField(primary_key=True, default=uuid4, unique=True, db_index=True)),
                ('map_asset',
                 fields.ForeignKeyField('depot.Asset', source_field='map_asset_id', null=True, db_constraint=True,
                                        to_field='id', related_name='locations', on_delete=OnDelete.SET_NULL)),
                ('name', fields.CharField(max_length=255)),
                ('description', fields.TextField(null=True, unique=False)),
                ('is_ausgabepflichtig', fields.BooleanField(default=False)),
            ],
            options={'table': 'depot_storage_location', 'app': 'depot', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='Tag',
            fields=[
                ('id', fields.UUIDField(primary_key=True, default=uuid4, unique=True, db_index=True)),
                ('name', fields.TextField(unique=False)),
                ('description', fields.TextField(unique=False)),
                ('color', fields.CharField(default='#000000', max_length=7)),
            ],
            options={'table': 'depot_tag', 'app': 'depot', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='Item',
            fields=[
                ('id', fields.UUIDField(primary_key=True, default=uuid4, unique=True, db_index=True)),
                ('report_profile',
                 fields.ForeignKeyField('depot.ReportProfile', source_field='report_profile_id', null=True,
                                        db_constraint=True, to_field='id', related_name='items',
                                        on_delete=OnDelete.RESTRICT)),
                ('group',
                 fields.ForeignKeyField('depot.ItemGroup', source_field='group_id', db_constraint=True, to_field='id',
                                        related_name='items', on_delete=OnDelete.RESTRICT)),
                ('storage_location',
                 fields.ForeignKeyField('depot.StorageLocation', source_field='storage_location_id', null=True,
                                        db_constraint=True, to_field='id', related_name='items',
                                        on_delete=OnDelete.RESTRICT)),
                ('assets', fields.ManyToManyField('depot.Asset', unique=True, db_constraint=True,
                                                  through='depot_item_depot_asset', forward_key='asset_id',
                                                  backward_key='depot_item_id', related_name='items',
                                                  on_delete=OnDelete.RESTRICT)),
                ('tags', fields.ManyToManyField('depot.Tag', null=True, unique=True, db_constraint=True,
                                                through='depot_item_depot_tag', forward_key='tag_id',
                                                backward_key='depot_item_id', related_name='items',
                                                on_delete=OnDelete.SET_NULL)),
                ('reservations', fields.ManyToManyField('depot.Reservation', unique=True, db_constraint=True,
                                                        through='models.item.reservation.ReservationLink',
                                                        forward_key='reservation_id', backward_key='item_id',
                                                        related_name='items', on_delete=OnDelete.CASCADE)),
                ('external_id', fields.CharField(unique=True, max_length=100)),
                ('created_at', fields.DatetimeField(auto_now=False, auto_now_add=True)),
                ('created_by', fields.UUIDField()),
                ('name', fields.TextField(unique=False)),
                ('description', fields.TextField(null=True, unique=False)),
                ('manufacturer', fields.TextField(null=True, unique=False)),
                ('model', fields.TextField(null=True, unique=False)),
                ('serial_number', fields.TextField(null=True, unique=False)),
                ('manufacture_date', fields.DatetimeField(null=True, auto_now=False, auto_now_add=False)),
                ('purchase_date', fields.DatetimeField(null=True, auto_now=False, auto_now_add=False)),
                ('first_use_date', fields.DatetimeField(null=True, auto_now=False, auto_now_add=False)),
                ('lendable', fields.BooleanField(
                    description='Shows if the item can actually be lent or not. Useful for items that are registered for documentation purposes only')),
                ('condition',
                 fields.CharEnumField(description='GOOD: good\nMONITOR: monitor\nREPAIR: repair\nGONE: gone',
                                      enum_type=Condition, max_length=7)),
            ],
            options={'table': 'depot_item', 'app': 'depot', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', fields.UUIDField(primary_key=True, default=uuid4, unique=True, db_index=True)),
                ('report_profile',
                 fields.ForeignKeyField('depot.ReportProfile', source_field='report_profile_id', db_constraint=True,
                                        to_field='id', related_name='reports', on_delete=OnDelete.RESTRICT)),
                ('item',
                 fields.ForeignKeyField('depot.Item', source_field='item_id', db_constraint=True, to_field='id',
                                        related_name='reports', on_delete=OnDelete.RESTRICT)),
                ('created_at', fields.DatetimeField(auto_now=False, auto_now_add=True)),
                ('created_by', fields.UUIDField()),
                ('updated_at', fields.DatetimeField(auto_now=True, auto_now_add=False)),
                ('updated_by', fields.UUIDField()),
                ('inspector', fields.UUIDField()),
                ('responsible_psa_expert', fields.UUIDField()),
                ('location', fields.CharField(null=True, max_length=255)),
                ('condition',
                 fields.CharEnumField(description='GOOD: good\nMONITOR: monitor\nREPAIR: repair\nGONE: gone',
                                      enum_type=Condition, max_length=50)),
                ('comment', fields.TextField(null=True, unique=False)),
            ],
            options={'table': 'depot_inspection_report', 'app': 'depot', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='ReservationLink',
            fields=[
                ('id', fields.UUIDField(primary_key=True, default=uuid4, unique=True, db_index=True)),
                ('reservation',
                 fields.ForeignKeyField('depot.Reservation', source_field='reservation_id', db_constraint=True,
                                        to_field='id', related_name='reservation', on_delete=OnDelete.CASCADE)),
                ('item',
                 fields.ForeignKeyField('depot.Item', source_field='item_id', db_constraint=True, to_field='id',
                                        related_name='items', on_delete=OnDelete.CASCADE)),
                ('borrowed', fields.DatetimeField(null=True, auto_now=False, auto_now_add=False)),
                ('borrowed_message', fields.TextField(null=True, unique=False)),
                ('returned', fields.DatetimeField(null=True, auto_now=False, auto_now_add=False)),
                ('returned_message', fields.TextField(null=True, unique=False)),
                ('collector', fields.TextField(description='The person who picked up the item', unique=False)),
            ],
            options={'table': 'depot_link_reservation__item', 'app': 'depot', 'pk_attr': 'id'},
            bases=['Model'],
        ),
    ]
